name: Build and Test

on:
  push:
    branches:
      - —Åi
      - master
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true 

      - name: Set up Conan
        uses: conan-io/conan-action@v2
        with:
          conan_version: 'latest'

      - name: Install dependencies
        run: |
          conan install . --output-folder=build --build=missing

      - name: Set up CMake
        uses: chihaoyuan/cmake-action@v1
        with:
          cmake_version: '3.22.0'

      - name: Build
        run: |
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ctest

      - name: Build Debian package
        run: |
          cd build
          cmake --build . --target build-deb
