name: Build and Test

on:
  push:
    branches:
      - —Åi
      - dev 
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true 

      - name: Install dependencies
        run: |
          conan install . --output-folder=build --build=missing

      - name: Build
        run: |
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ctest

      - name: Build Debian package
        run: |
          cd build
          cmake --build . --target build-deb
